# Generated by Django 5.0 on 2023-12-06 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('number_home', models.PositiveIntegerField(verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('model', models.CharField(max_length=100, verbose_name='модел')),
                ('release_date', models.DateField(verbose_name='дата выхода')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.contact', verbose_name='контакты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.networknode', verbose_name='поставщик')),
                ('products', models.ManyToManyField(to='trading.product', verbose_name='продукты')),
            ],
            options={
                'verbose_name': 'сеть',
                'verbose_name_plural': 'сети',
            },
        ),
    ]
