# Generated by Django 5.0 on 2023-12-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_networknode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='type_network',
            field=models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('individual_entrepreneur', 'Индивидуальный предприниматель')], default='Завод', max_length=100, verbose_name='тип объекта сети'),
        ),
    ]
